### ISSUE TITLE
No package named dotenv. Need to update the requirements from dotenv to python-dotenv

### ISSUE THREAD

**Issue by jerinkumar** [piyush-singhal/oauth-python#1]
No package named dotenv. Need to update the requirements from dotenv to python-dotenv

**Comment by piyush-singhal** [comment]
Hi @jerinkumar, Thank you for creating an issue. I fixed this issue and pushed one commit. Can you please confirm if this fix is working for you? Once you confirm, I will close the issue.

Again Thanks!!

**Comment by jerinkumar** [comment]
Hi Piyush, Thanks. It works fine. You can close it 👍
